package com.icarus.events;

import android.annotation.SuppressLint;
import android.content.Context;
import android.content.Intent;
import android.graphics.Color;
import android.graphics.drawable.GradientDrawable;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageButton;
import android.widget.ImageView;
import android.widget.TextView;
import android.widget.Toast;

import androidx.annotation.NonNull;
import androidx.recyclerview.widget.RecyclerView;

import com.google.firebase.firestore.CollectionReference;
import com.google.firebase.firestore.DocumentReference;
import com.google.firebase.firestore.DocumentSnapshot;
import com.google.firebase.firestore.FieldValue;
import com.google.firebase.firestore.FirebaseFirestore;
import com.google.firebase.firestore.SetOptions;
import com.google.firebase.firestore.WriteBatch;
import com.squareup.picasso.Picasso;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;

/**
 * ArrayAdapter used in the administrator dashboard to display events in a ListView.
 * <p>
 * Binds Event objects to the event list item layout and provides administrator
 * controls for viewing event details and removing events from Firebase Firestore.
 *
 * @author Benjamin Hall
 */
public class AdministratorDashboardEventArrayAdapter extends RecyclerView.Adapter<AdministratorDashboardEventArrayAdapter.ViewHolder> {
    private ArrayList<Event> events;
    private Context context;
    private FirebaseFirestore db;
    Map<String, String> categoryColors;

    /**
     * ViewHolder for the event list items.
     */
    public static class ViewHolder extends RecyclerView.ViewHolder {
        TextView eventName;
        TextView eventCategory;
        TextView eventDate;
        ImageButton removeEventButton;
        ImageView posterView;

        public ViewHolder(@NonNull View itemView) {
            super(itemView);
            eventName = itemView.findViewById(R.id.admin_dashboard_event_list_event_name);
            eventCategory = itemView.findViewById(R.id.admin_dashboard_event_list_event_category);
            eventDate = itemView.findViewById(R.id.admin_dashboard_event_list_event_date);
            posterView = itemView.findViewById(R.id.admin_dashboard_event_list_poster);
            removeEventButton = itemView.findViewById(R.id.admin_dashboard_event_list_remove_event_button);
        }
    }

    /**
     * Constructs an adapter for displaying Event objects in the administrator
     * dashboard event list.
     *
     * @param context the context used to inflate views and access resources
     * @param events  the list of events to be displayed by the adapter
     */
    public AdministratorDashboardEventArrayAdapter(Context context, ArrayList<Event> events, Map<String, String> categoryColors) {
        this.events = events;
        this.context = context;
        this.categoryColors = categoryColors != null ? categoryColors : new HashMap<>();
        this.db = FirebaseFirestore.getInstance();
    }

    @NonNull
    @Override
    public ViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
        View view = LayoutInflater.from(context)
                .inflate(R.layout.administrator_dashboard_event_list_content, parent, false);
        return new ViewHolder(view);
    }

    @SuppressLint("ResourceType")
    @Override
    public void onBindViewHolder(@NonNull ViewHolder holder, int position) {
        Event event = events.get(position);

        // Apply rotating accent color to poster background
        int[] accentColors = {
                context.getColor(R.color.accent_third),
                context.getColor(R.color.accent_second),
                context.getColor(R.color.accent_first)
        };

        //holder.textContainer.setBackgroundColor(accentColors[position % accentColors.length]);
        //((MaterialCardView) holder.itemView).setStrokeColor(accentColors[position % accentColors.length]);
        //((MaterialCardView) holder.itemView).setStrokeColor(accentColors[0]);
        // Load poster image
        if (event.getImage() != null && !event.getImage().trim().isEmpty()) {
            Picasso.get()
                    .load(event.getImage())
                    .error(R.drawable.poster)           // Optional: shows if link fails
                    .into(holder.posterView);
        } else {
            holder.posterView.setImageResource(R.drawable.poster);
        }

        holder.eventName.setText(event.getName());
        holder.eventCategory.setText(event.getCategory());

        // Generated by chatGPT Mar 28th 2026,
        // "How can I safely parse my category color into the background of the category?"
        GradientDrawable chipBackground =
                (GradientDrawable) holder.eventCategory.getBackground().mutate();
        // reset to default first
        chipBackground.setColor(Color.parseColor(context.getString(R.color.accent_first)));
        // Get attached color
        String hexColor = categoryColors.get(event.getCategory());
        if (hexColor != null && !hexColor.trim().isEmpty()) {
            try {
                chipBackground =
                        (GradientDrawable) holder.eventCategory.getBackground().mutate();
                chipBackground.setColor(Color.parseColor(hexColor));
            } catch (IllegalArgumentException ignored) {
            }
        }

        // Reformatting date to be more readable and convert to string
        if (event.getDate() != null) {
            SimpleDateFormat formatter = new SimpleDateFormat("MMM d, yyyy", Locale.getDefault());
            String dateString = formatter.format(event.getDate());
            holder.eventDate.setText(dateString);
        } else {
            holder.eventDate.setText(R.string.entrant_event_list_missing_date);
        }

        // Navigate to event details
        holder.itemView.setOnClickListener(v -> {
            Intent intent = new Intent(context, EventDetailsActivity.class);
            intent.putExtra("eventId", event.getId());
            context.startActivity(intent);
        });

        holder.removeEventButton.setOnClickListener(v -> {
            // Code generated by Claude AI March 11, 2026
            // "How to remove event ID from a users list of events for each user document in the
            // events 'entrants' subcollection."
            CollectionReference eventEntrantsRef = db.collection(FirestoreCollections.EVENTS_COLLECTION).document(event.getId()).collection("entrants");
            CollectionReference eventCommentsRef = db.collection(FirestoreCollections.EVENTS_COLLECTION).document(event.getId()).collection("comments");
            CollectionReference eventNotificationsRef = db.collection(FirestoreCollections.EVENTS_COLLECTION).document(event.getId()).collection("notifications");

            com.google.android.gms.tasks.Task<com.google.firebase.firestore.QuerySnapshot> entrantsTask = eventEntrantsRef.get();
            com.google.android.gms.tasks.Task<com.google.firebase.firestore.QuerySnapshot> commentsTask = eventCommentsRef.get();
            com.google.android.gms.tasks.Task<com.google.firebase.firestore.QuerySnapshot> notificationsTask = eventNotificationsRef.get();

            com.google.android.gms.tasks.Tasks.whenAllSuccess(entrantsTask, commentsTask, notificationsTask)
                    .addOnSuccessListener(results -> {
                        WriteBatch batch = db.batch();

                        com.google.firebase.firestore.QuerySnapshot userSnapshots = (com.google.firebase.firestore.QuerySnapshot) results.get(0);
                        com.google.firebase.firestore.QuerySnapshot commentSnapshots = (com.google.firebase.firestore.QuerySnapshot) results.get(1);
                        com.google.firebase.firestore.QuerySnapshot notificationSnapshots = (com.google.firebase.firestore.QuerySnapshot) results.get(2);

                        // Remove event from each user's events array and delete entrant docs
                        for (DocumentSnapshot userDoc : userSnapshots.getDocuments()) {
                            DocumentReference userRef = db.collection(FirestoreCollections.USERS_COLLECTION).document(userDoc.getId());
                            Map<String, Object> updateData = new HashMap<>();
                            updateData.put("events", FieldValue.arrayRemove(event.getId()));
                            batch.set(userRef, updateData, SetOptions.merge());
                            batch.delete(userDoc.getReference());
                        }

                        // Delete all comment documents
                        for (DocumentSnapshot commentDoc : commentSnapshots.getDocuments()) {
                            batch.delete(commentDoc.getReference());
                        }

                        // Delete all notification documents
                        for (DocumentSnapshot notificationDoc : notificationSnapshots.getDocuments()) {
                            batch.delete(notificationDoc.getReference());
                        }

                        // Remove the event's poster from the database
                        db.collection(FirestoreCollections.IMAGES_COLLECTION)
                                .whereEqualTo("URL", event.getImage())
                                .get()
                                .addOnSuccessListener(querySnapshot -> {
                                    for (DocumentSnapshot doc : querySnapshot.getDocuments()) {
                                        new Image(event.getImage(), doc.getId()).delete(context, db);
                                    }
                                });

                        // Delete event document and commit
                        batch.delete(db.collection(FirestoreCollections.EVENTS_COLLECTION).document(event.getId()));

                        batch.commit()
                                .addOnSuccessListener(aVoid -> {
                                    Log.d("Firestore", "Event deleted successfully");
                                    Toast.makeText(context, "Event deleted", Toast.LENGTH_SHORT).show();
                                })
                                .addOnFailureListener(e -> {
                                    Log.e("Firestore", "Error deleting event", e);
                                    Toast.makeText(context, "Failed to delete event", Toast.LENGTH_SHORT).show();
                                });

                    }).addOnFailureListener(e -> Log.e("Firestore", "Error fetching subcollections", e));
        });
    }

    @Override
    public int getItemCount() {
        return events.size();
    }
}
