package com.icarus.events;

import android.content.Context;
import android.content.Intent;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ArrayAdapter;
import android.widget.Button;
import android.widget.ImageButton;
import android.widget.TextView;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

import com.google.firebase.firestore.DocumentReference;
import com.google.firebase.firestore.FirebaseFirestore;
import com.google.firebase.firestore.WriteBatch;

import java.util.ArrayList;

public class AdministratorDashboardUserArrayAdapter extends ArrayAdapter<User> {
    private ArrayList<User> users;
    private Context context;
    private FirebaseFirestore db;

    public AdministratorDashboardUserArrayAdapter(Context context, ArrayList<User> users){
        super(context, 0, users);
        this.users = users;
        this.context = context;
        this.db = FirebaseFirestore.getInstance();
    }

    @NonNull
    public View getView(int position, @Nullable View convertView, @NonNull ViewGroup parent){
        View view = convertView;
        if (view == null){
            view = LayoutInflater.from(context)
                    .inflate(R.layout.administrator_dashboard_user_list_content, parent, false);
        }

        User user = users.get(position);
        TextView userName = view
                .findViewById(R.id.admin_dashboard_user_list_user_name);
        Button userDetailsButton = view
                .findViewById(R.id.admin_dashboard_user_list_user_details_button);
        ImageButton removeUserButton = view
                .findViewById(R.id.admin_dashboard_user_list_remove_user_button);

        userName.setText(user.getName());

        userDetailsButton.setOnClickListener(v -> {
//            Intent intent = new Intent(context, UserProfileActivity.class);
//            intent.putExtra("userId", user.getId());
//            context.startActivity(intent);
        });

        removeUserButton.setOnClickListener(v -> {
            // Code generated by Claude AI March 11, 2026
            // "How to remove user document from events 'entrants' sub collection for each event
            // in the users event array."
            DocumentReference userRef = db.collection("users").document(user.getId());

            userRef.get().addOnSuccessListener(userSnapshot -> {
                if (!userSnapshot.exists()) return;

                ArrayList<String> events = (ArrayList<String>) userSnapshot.get("events");

                if (events == null || events.isEmpty()) {
                    userRef.delete();
                    return;
                }

                WriteBatch batch = db.batch();

                // Delete user document in each events 'entrants' sub-collection
                for (String eventId : events) {
                    DocumentReference entrantRef = db.collection("events").document(eventId)
                                                    .collection("entrants").document(user.getId());
                    batch.delete(entrantRef);
                }

                // Delete the user
                batch.delete(userRef);

                // Commit the batch
                batch.commit()
                        .addOnSuccessListener(aVoid -> Log.d("Firestore", "User deleted successfully"))
                        .addOnFailureListener(e -> Log.e("Firestore", "Error deleting user", e));
            }).addOnFailureListener(e -> Log.e("Firestore", "Error fetching user", e));

        });

        return view;
    }
}
