package com.icarus.events;

import static androidx.core.content.ContextCompat.startActivity;

import android.content.Context;
import android.content.Intent;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ArrayAdapter;
import android.widget.Button;
import android.widget.ImageButton;
import android.widget.LinearLayout;
import android.widget.TextView;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

import com.google.firebase.firestore.CollectionReference;
import com.google.firebase.firestore.DocumentReference;
import com.google.firebase.firestore.DocumentSnapshot;
import com.google.firebase.firestore.FieldValue;
import com.google.firebase.firestore.FirebaseFirestore;
import com.google.firebase.firestore.WriteBatch;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Locale;

/**
 * ArrayAdapter used in the administrator dashboard to display events in a ListView.
 * <p>
 * Binds Event objects to the event list item layout and provides administrator
 * controls for viewing event details and removing events from Firebase Firestore.
 *
 * @author Benjamin Hall
 */
public class AdministratorDashboardEventArrayAdapter extends ArrayAdapter<Event> {
    private ArrayList<Event> events;
    private Context context;
    private FirebaseFirestore db;

    /**
     * Constructs an adapter for displaying Event objects in the administrator
     * dashboard event list.
     *
     * @param context the context used to inflate views and access resources
     * @param events the list of events to be displayed by the adapter
     */
    public AdministratorDashboardEventArrayAdapter(Context context, ArrayList<Event> events){
        super(context, 0, events);
        this.events = events;
        this.context = context;
        this.db = FirebaseFirestore.getInstance();
    }

    /**
     * Returns a view for displaying an event in the administrator event list.
     * <p>
     * Inflates the list item layout if necessary, binds the data to the UI
     * components, and configures actions for viewing event details and
     * removing the event from the database.
     *
     * @param position the position of the event in the adapter's data set
     * @param convertView a view to reuse
     * @param parent the parent view that this view will be attached to
     * @return the view representing the event at the specified position
     */
    @NonNull
    public View getView(int position, @Nullable View convertView, @NonNull ViewGroup parent){
        View view = convertView;
        if (view == null){
            view = LayoutInflater.from(context)
                    .inflate(R.layout.administrator_dashboard_event_list_content, parent, false);
        }

        // Initializing views
        Event event = events.get(position);
        TextView eventName = view
                .findViewById(R.id.admin_dashboard_event_list_event_name);
        LinearLayout eventDetails = view
                .findViewById(R.id.admin_dashboard_event_list_details_layout);
        ImageButton removeEventButton = view
                .findViewById(R.id.admin_dashboard_event_list_remove_event_button);
        TextView eventCategory = view.findViewById(R.id.admin_dashboard_event_list_event_category);
        TextView eventDate = view.findViewById(R.id.admin_dashboard_event_list_event_date);

        // Setting event details values
        eventName.setText(event.getName());
        eventCategory.setText(event.getCategory());
        // Reformatting date to be more readable and convert to string
        if (event.getDate() != null) {
            SimpleDateFormat formatter = new SimpleDateFormat("MMM d, yyyy", Locale.getDefault());
            String dateString = formatter.format(event.getDate());
            eventDate.setText(dateString);
        } else {
            eventDate.setText(R.string.entrant_event_list_missing_date);
        }

        // Initializing click listeners
        eventDetails.setOnClickListener(v -> {
            Intent intent = new Intent(context, EventDetailsActivity.class);
            intent.putExtra("eventId", event.getId());
            context.startActivity(intent);
        });

        removeEventButton.setOnClickListener(v -> {
            // Code generated by Claude AI March 11, 2026
            // "How to remove event ID from a users list of events for each user document in the
            // events 'entrants' subcollection."
            CollectionReference eventEntrantsRef = db.collection(FirestoreCollections.EVENTS_COLLECTION).document(event.getId()).collection("entrants");
            eventEntrantsRef.get().addOnSuccessListener(userSnapshots -> {
                WriteBatch batch = db.batch();

                // remove event from each user's events array
                for (DocumentSnapshot userDoc : userSnapshots.getDocuments()) {
                    String userId = userDoc.getId();
                    DocumentReference userRef = db.collection(FirestoreCollections.USERS_COLLECTION).document(userId);
                    batch.update(userRef, "events", FieldValue.arrayRemove(event.getId()));
                }

                // remove event document
                DocumentReference eventRef = db.collection(FirestoreCollections.EVENTS_COLLECTION).document(event.getId());
                batch.delete(eventRef);

                // commit the batch
                batch.commit()
                        .addOnSuccessListener(aVoid -> Log.d("Firestore", "Event deleted successfully"))
                        .addOnFailureListener(e -> Log.e("Firestore", "Error deleting event", e));
            }).addOnFailureListener(e -> Log.e("Firestore", "Error fetching event users", e));

        });

        return view;
    }
}
