package com.icarus.events;

import android.content.Context;
import android.content.Intent;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ArrayAdapter;
import android.widget.Button;
import android.widget.ImageButton;
import android.widget.TextView;
import android.widget.Toast;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

import com.google.firebase.firestore.DocumentReference;
import com.google.firebase.firestore.FirebaseFirestore;
import com.google.firebase.firestore.WriteBatch;

import java.util.ArrayList;

/**
 * Adapter used in the administrator dashboard to display users in a ListView.
 * <p>
 * Binds User objects to the user list item layout and provides administrator
 * controls for viewing user details and removing users from Firebase Firestore.
 *
 * @author Benjamin Hall
 */
public class AdministratorDashboardUserArrayAdapter extends ArrayAdapter<User> {
    private ArrayList<User> users;
    private Context context;
    private FirebaseFirestore db;

    /**
     * Constructs an adapter for displaying User objects in the administrator
     * dashboard user list.
     *
     * @param context the context used to inflate views and access resources
     * @param users the list of users to be displayed by the adapter
     */
    public AdministratorDashboardUserArrayAdapter(Context context, ArrayList<User> users){
        super(context, 0, users);
        this.users = users;
        this.context = context;
        this.db = FirebaseFirestore.getInstance();
    }

    /**
     * Returns a view for displaying a user in the administrator user list.
     * <p>
     * Inflates the list item layout if necessary, binds the data to the UI
     * components, and configures actions for viewing user details and
     * removing the user from the database.
     *
     * @param position the position of the user in the adapter's data set
     * @param convertView a view to reuse
     * @param parent the parent view that this view will be attached to
     * @return the view representing the user at the specified position
     */
    @NonNull
    public View getView(int position, @Nullable View convertView, @NonNull ViewGroup parent){
        View view = convertView;
        if (view == null){
            view = LayoutInflater.from(context)
                    .inflate(R.layout.administrator_dashboard_user_list_content, parent, false);
        }

        User user = users.get(position);
        TextView userName = view
                .findViewById(R.id.admin_dashboard_user_list_user_name);
        ImageButton removeUserButton = view
                .findViewById(R.id.admin_dashboard_user_list_remove_user_button);

        userName.setText(user.getName());

        userName.setOnClickListener(v -> {
            if (user.getId().equals(UserSession.getInstance().getCurrentUser().getId())) {
                Toast.makeText(context, "You cannot access your own account from this menu", Toast.LENGTH_SHORT).show();
                return;
            }
            Intent intent = new Intent(context, UserProfileActivity.class);
            intent.putExtra("deviceId", user.getId());
            context.startActivity(intent);
        });

        removeUserButton.setOnClickListener(v -> {
            // Prevent admin from deleting his own profile from here
            if (user.getId().equals(UserSession.getInstance().getCurrentUser().getId())) {
                Toast.makeText(context, "You cannot delete your own account", Toast.LENGTH_SHORT).show();
                return;
            }
            // Code generated by Claude AI March 11, 2026
            // "How to remove user document from events 'entrants' sub collection for each event
            // in the users event array."
            DocumentReference userRef = db.collection(FirestoreCollections.USERS_COLLECTION).document(user.getId());

            userRef.get().addOnSuccessListener(userSnapshot -> {
                if (!userSnapshot.exists()) return;

                ArrayList<String> events = (ArrayList<String>) userSnapshot.get("events");

                if (events == null || events.isEmpty()) {
                    userRef.delete();
                    return;
                }

                WriteBatch batch = db.batch();

                // Delete user document in each events 'entrants' sub-collection
                for (String eventId : events) {
                    DocumentReference entrantRef = db.collection(FirestoreCollections.EVENTS_COLLECTION).document(eventId)
                                                    .collection("entrants").document(user.getId());
                    batch.delete(entrantRef);
                }

                // Delete the user
                batch.delete(userRef);

                // Commit the batch
                batch.commit()
                        .addOnSuccessListener(aVoid -> Log.d("Firestore", "User deleted successfully"))
                        .addOnFailureListener(e -> Log.e("Firestore", "Error deleting user", e));
            }).addOnFailureListener(e -> Log.e("Firestore", "Error fetching user", e));

        });

        return view;
    }
}
