package com.icarus.events;

import android.content.Context;
import android.graphics.Color;
import android.graphics.drawable.GradientDrawable;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;

import androidx.annotation.NonNull;
import androidx.recyclerview.widget.RecyclerView;

import com.squareup.picasso.Picasso;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;

// This arrayAdapter was adapted to use RecyclerView by consulting ChatGPT on March 26th, 2026,
// " How to improve my event list page to use a different view that
// allows better customization for scrolling and elevation"
/**
 * Adapter used to display events in the entrant event list.
 * <p>
 * Binds Event objects to the entrant event list item layout and displays
 * event information such as poster image, name, category, category color,
 * and formatted event date.
 *
 * @author Alex Alves
 */
public class EntrantEventListArrayAdapter extends RecyclerView.Adapter<EntrantEventListArrayAdapter.ViewHolder> {
    private ArrayList<Event> events;
    private Context context;
    private OnItemClickListener listener;
    private Map<String, String> categoryColors;


    /**
     * Listener interface for handling clicks on event list items.
     */
    public interface OnItemClickListener {
        /**
         * Called when an event item is clicked.
         *
         * @param position the adapter position of the clicked item
         */
        void onItemClick(int position);
    }

    /**
     * Constructs an adapter for displaying Event objects in the entrant event list.
     *
     * @param context the context used to inflate views and access resources
     * @param events the list of events to be displayed by the adapter
     * @param listener the listener invoked when an event item is clicked
     * @param categoryColors a mapping of category names to hex color strings
     */
    public EntrantEventListArrayAdapter(Context context, ArrayList<Event> events, OnItemClickListener listener, Map<String, String> categoryColors) {
        this.events = events;
        this.context = context;
        this.listener = listener;
        this.categoryColors = categoryColors != null ? categoryColors : new HashMap<>();
    }

    /**
     * Creates a new ViewHolder for an entrant event list item.
     *
     * @param parent the parent ViewGroup that the new view will be attached to
     * @param viewType the view type of the new view
     * @return a ViewHolder containing the inflated event item view
     */
    @NonNull
    @Override
    public ViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
        View view = LayoutInflater.from(context)
                .inflate(R.layout.entrant_event_list_content, parent, false);
        return new ViewHolder(view);
    }

    /**
     * Returns a view for displaying an event in the entrant event list.
     * Inflates the list item layout if necessary and binds the event's
     * name, category, and formatted date to the corresponding UI elements.
     *
     * @param holder the ViewHolder to bind data to
     * @param position the position of the event in the adapter's data set
     */
    @Override
    public void onBindViewHolder(@NonNull ViewHolder holder, int position) {
        Event event = events.get(position);

        // Apply rotating accent color to poster background
        int[] accentColors = {
                context.getColor(R.color.accent_third),
                context.getColor(R.color.accent_second),
                context.getColor(R.color.accent_first)
        };

        //holder.textContainer.setBackgroundColor(accentColors[position % accentColors.length]);
        //((MaterialCardView) holder.itemView).setStrokeColor(accentColors[position % accentColors.length]);
        //((MaterialCardView) holder.itemView).setStrokeColor(accentColors[0]);
        // Load poster image
        if (event.getImage() != null && !event.getImage().trim().isEmpty()) {
            Picasso.get()
                    .load(event.getImage())
                    .error(R.drawable.poster)           // Optional: shows if link fails
                    .into(holder.posterView);
        } else {
            holder.posterView.setImageResource(R.drawable.poster);
        }

        holder.eventName.setText(event.getName());
        holder.eventCategory.setText(event.getCategory());

        // Generated by chatGPT Mar 28th 2026,
        // "How can I safely parse my category color into the background of the category?"
        GradientDrawable chipBackground =
                (GradientDrawable) holder.eventCategory.getBackground().mutate();
        // reset to default first
        chipBackground.setColor(Color.parseColor(context.getString(R.color.accent_first)));
        // Get attached color
        String hexColor = categoryColors.get(event.getCategory());
        if (hexColor != null && !hexColor.trim().isEmpty()) {
            try {
                chipBackground =
                        (GradientDrawable) holder.eventCategory.getBackground().mutate();
                chipBackground.setColor(Color.parseColor(hexColor));
            } catch (IllegalArgumentException ignored) {
            }
        }

        // Reformatting date to be more readable and convert to string
        if (event.getStartDate() != null) {
            SimpleDateFormat formatter = new SimpleDateFormat("MMM d, yyyy", Locale.getDefault());
            String dateString = formatter.format(event.getStartDate());
            holder.eventDate.setText(dateString);
        } else {
            holder.eventDate.setText(R.string.entrant_event_list_missing_date);
        }

        holder.itemView.setOnClickListener(v -> listener.onItemClick(position));
    }

    /**
     * Returns the number of events currently displayed by the adapter.
     *
     * @return the total number of event items
     */
    @Override
    public int getItemCount() {
        return events.size();
    }

    /**
     * ViewHolder that stores references to the views for a single event item.
     */
    public static class ViewHolder extends RecyclerView.ViewHolder {
        TextView eventName, eventCategory, eventDate;
        ImageView posterView;
        LinearLayout textContainer;

        /**
         * Constructs a ViewHolder for a single entrant event list item view.
         *
         * @param view the item view containing the event UI elements
         */
        public ViewHolder(@NonNull View view) {
            super(view);
            eventName = view.findViewById(R.id.entrant_event_list_event_name);
            eventCategory = view.findViewById(R.id.entrant_event_list_event_category);
            eventDate = view.findViewById(R.id.entrant_event_list_event_date);
            posterView = view.findViewById(R.id.entrant_event_list_poster);
            textContainer = view.findViewById(R.id.entrant_event_list_text_container);
        }
    }
}